### ISSUE TITLE
Fails to detect iOS > 9

### ISSUE THREAD

**Issue by chrism2671** [tuvistavie/elixir-browser#18]
Regex only allows grabbing one digit, it should be 1 or more.

**Comment by chrism2671** [comment]
Test string:
"Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1"

PR submitted.

**Comment by chrism2671** [comment]
(PR submitted)

**Comment by danhper** [comment]
Thanks for the PR. I uploaded a new version to hex.
