### ISSUE TITLE
protocol Enumerable not implemented for nil

### ISSUE THREAD

**Issue by ewitchin** [tuvistavie/elixir-browser#2]
For some reason some people in my application are getting a weird UA string which then causes and exception to be raised for "protocol Enumerable not implemented for nil" when calling Browser.full_version

Here is the UA string:
Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/13.1.72140 Mobile/13F69 Safari/600.1.4

**Comment by danhper** [comment]
@ewitchin Hi, thanks for reporting!
I had no problem reproducing, I am going to check what is happening.

**Comment by danhper** [comment]
It seems that the `GSA/version` pattern did not exist, I just added it and published a new version.
Please let me know if you run into any other issue! :smile:

**Comment by ewitchin** [comment]
Thanks for resolving the issue so fast!

**Comment by ewitchin** [comment]
tutistavie, I am still receiving these type of errors due to bots hitting the website and the UA being something very weird. I can try to capture some of the UAs for you, but was just wondering if we could somehow add a generic "Other" if the lookup failed so lib/browser.ex:104: Browser.full_version/1 failed with a (Protocol.UndefinedError) protocol Enumerable not implemented for nil would not through. Let me know your thoughts.

**Comment by danhper** [comment]
Thanks for the feedback!
I just published version 0.1.5 with a fix for this.
Invalid versions should now return `"0.0"`, let me know if that works for you :smile:

**Comment by ewitchin** [comment]
Works for me. I will let you know if I have any issues. Thanks for the great package!!
