### ISSUE TITLE
Possibly invalid detections for some useragents

### ISSUE THREAD

**Issue by rblack** [tuvistavie/elixir-browser#3]
Hi!
I've recently tested elixir-browser and found some possibly invalid detections. Useragents in this [list](https://gist.github.com/rblack/c3fb4d9cd85dbb34af9ffd184030b06e) are detected neither as mobile nor tablet. Most of them seem completely valid.
I thought you may find this info usefull, otherwise I'm sorry and you may close the issue.

**Comment by danhper** [comment]
Hi, sorry for the late reply and thank you for reporting.
I am going to see what I can do about it!

**Comment by JamieREvans** [comment]
Was this issue resolved? If not, let me know how I can help.
